import {test,expect} from '@playwright/test';
test.beforeEach(async({page})=>{await page.goto('/admin/');await page.getByLabel('Username').fill(process.env.FLUSSONIX_ADMIN_USER||'admin');await page.getByLabel('Password',{exact:true}).fill(process.env.FLUSSONIX_ADMIN_PASSWORD!);await page.getByRole('button',{name:'Sign in',exact:true}).click();await expect(page.getByRole('heading',{name:'Streams',exact:true})).toBeVisible();});
test('create owned stream and show persisted operational state',async({page})=>{await page.getByRole('button',{name:'Add stream'}).click();await page.getByLabel('Stream name',{exact:true}).fill('ui-test');await page.getByLabel('Input URL',{exact:true}).fill('testsrc://');await page.getByRole('button',{name:'Save',exact:true}).click();await expect(page.getByRole('heading',{name:'ui-test',exact:true})).toBeVisible();await page.getByRole('button',{name:'← Streams'}).click();await expect(page.getByRole('button',{name:'ui-test',exact:true})).toBeVisible();await page.screenshot({path:'../.runtime/screenshots/streams.png',fullPage:true});});
test('configuration edits can be validated without applying',async({page})=>{await page.getByRole('button',{name:'Config',exact:true}).click();const editor=page.getByLabel('Server configuration JSON');await expect(editor).toHaveValue(/"streams"/);const original=await editor.inputValue();const data=JSON.parse(original);data.streams=[];await editor.fill(JSON.stringify(data,null,2));await expect(page.getByRole('button',{name:'Validate',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Validate',exact:true}).click();await expect(page.getByRole('status')).toContainText('Saved state has not changed');});
test('cluster and template screens use configured data',async({page})=>{await page.getByRole('button',{name:'Templates',exact:true}).click();await expect(page.getByRole('heading',{name:'Templates',exact:true})).toBeVisible();await page.getByRole('button',{name:'Cluster',exact:true}).click();await expect(page.getByText('Viewer entry point',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Source servers',exact:true}).click();await expect(page.getByText('No sources configured')).toBeVisible();await page.screenshot({path:'../.runtime/screenshots/cluster.png',fullPage:true});});
test('editing a title preserves template inheritance',async({page,request})=>{
 const headers={Authorization:'Basic '+Buffer.from((process.env.FLUSSONIX_ADMIN_USER||'admin')+':'+process.env.FLUSSONIX_ADMIN_PASSWORD).toString('base64')};
 const template='ui-inheritance',stream='ui-inherited';
 expect((await request.put('/streamer/api/v3/templates/'+template,{headers,data:{static:false,inputs:[{url:'testsrc://'}]}})).ok()).toBeTruthy();
 expect((await request.put('/streamer/api/v3/streams/'+stream,{headers,data:{$reset:true,template}})).ok()).toBeTruthy();
 await expect(page.getByRole('button',{name:stream,exact:true})).toBeVisible();
 await page.getByRole('button',{name:stream,exact:true}).click(); await page.getByRole('button',{name:'Edit stream',exact:true}).click();
 const editor=page.getByLabel('Configuration JSON'); const explicit=JSON.parse(await editor.inputValue());
 expect(explicit.inputs).toBeUndefined(); expect(explicit.static).toBeUndefined(); explicit.title='A title edit'; await editor.fill(JSON.stringify(explicit));
 await page.getByRole('button',{name:'Save',exact:true}).click(); await expect(page.getByRole('heading',{name:'A title edit',exact:true})).toBeVisible();
 expect((await request.put('/streamer/api/v3/templates/'+template,{headers,data:{inputs:[{url:'hls://example.net/updated.m3u8'}]}})).ok()).toBeTruthy();
 const effective=await (await request.get('/streamer/api/v3/streams/'+stream,{headers})).json(); expect(effective.inputs[0].url).toBe('hls://example.net/updated.m3u8'); expect(effective.config_on_disk.inputs).toBeUndefined();
});
test('auth tab reauthorizes and closes an actual viewer session',async({page,request})=>{
 const headers={Authorization:'Basic '+Buffer.from((process.env.FLUSSONIX_ADMIN_USER||'admin')+':'+process.env.FLUSSONIX_ADMIN_PASSWORD).toString('base64')};
 const name='ui-session-'+Date.now();
 expect((await request.put('/streamer/api/v3/streams/'+name,{headers,data:{$reset:true,static:false,inputs:[{url:'testsrc://'}]}})).ok()).toBeTruthy();
 const media=await request.get('/'+name+'/index.m3u8?token=browser-viewer');expect(media.status()).toBe(200);
 await expect(page.getByRole('button',{name,exact:true})).toBeVisible();await page.getByRole('button',{name,exact:true}).click();await page.getByRole('button',{name:'Auth',exact:true}).click();
 await expect(page.getByRole('heading',{name:'Viewer sessions',exact:true})).toBeVisible();
 await expect(page.getByRole('cell',{name:'hls',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Reauthorize sessions',exact:true}).click();await expect(page.getByRole('status')).toContainText('Reauthorized 1 session');
 await page.getByRole('button',{name:'Close session',exact:true}).click();await expect(page.getByRole('status')).toContainText('Session closed');
 await expect(page.getByText('No active viewer sessions', {exact:true})).toBeVisible();
 expect((await request.get('/'+name+'/index.m3u8?token=browser-viewer')).status()).toBe(403);
});
