import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import Hls from 'hls.js';
import './style.css';
type Item=Record<string,any>;
type View='streams'|'templates'|'config'|'cluster';
const api='/streamer/api/v3/';const native='/flussonix/api/v1/';
const pct=(n:unknown)=>typeof n==='number'?`${(n*100).toFixed(1)}%`:'—';
const mbps=(n:unknown)=>typeof n==='number'?`${n.toFixed(2)} Mb/s`:'—';
const path=(s:string)=>s.split('/').map(encodeURIComponent).join('/');
function App(){
 const[credentials,setCredentials]=useState('');const[user,setUser]=useState('admin');const[password,setPassword]=useState('');
 const[view,setView]=useState<View>('streams');const[items,setItems]=useState<Item[]>([]);const[templates,setTemplates]=useState<Item[]>([]);const[node,setNode]=useState<Item>({});const[caps,setCaps]=useState<Item>({});
 const[search,setSearch]=useState('');const[filter,setFilter]=useState('all');const[tab,setTab]=useState('overview');const[selected,setSelected]=useState<Item|null>(null);const[editing,setEditing]=useState<Item|null>(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);const[dirty,setDirty]=useState(false);const[json,setJson]=useState('');const[config,setConfig]=useState<Item>({});const[resource,setResource]=useState('peers');const[play,setPlay]=useState<string|null>(null);
 async function request(url:string,method='GET',body?:any,credential=credentials){const r=await fetch(url,{method,headers:{Authorization:`Basic ${credential}`,...(body!==undefined?{'Content-Type':'application/json'}:{})},body:body!==undefined?JSON.stringify(body):undefined});if(r.status===401){setCredentials('');throw Error('Check your management username and password.')}if(!r.ok){const b=await r.json().catch(()=>({}));throw Error(b.errors?.map((e:Item)=>e.message).join('; ')||`Request failed (${r.status})`);}return r.status===204?{}:r.json();}
 async function load(){if(!credentials)return;try{const[n,c]=await Promise.all([request(native+'node'),request(native+'capabilities')]);setNode(n);setCaps(c);if(view==='streams'||view==='templates'){let data:Item[]=[];let cursor:string|null=null;do{const page=await request(api+view+'?limit=1000'+(cursor?'&cursor='+encodeURIComponent(cursor):''));data.push(...page[view]);cursor=page.next;}while(cursor&&data.length<10000);setItems(data);setSelected(previous=>previous?data.find(i=>i.name===previous.name)||previous:null);const t=await request(api+'templates');setTemplates(t.templates);}else{const c=await request(api+'config');setConfig(c);if(view==='cluster')setItems(c[resource]||[]);}setError('');}catch(e){setError(String((e as Error).message));}}
 useEffect(()=>{load();const timer=setInterval(()=>{if(!document.hidden)load()},3000);return()=>clearInterval(timer)},[credentials,view,resource]);
 useEffect(()=>{if(view==='config'&&!dirty)setJson(JSON.stringify(config,null,2))},[view,config,dirty]);
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);const c=btoa(user+':'+password);try{await request(native+'node','GET',undefined,c);setCredentials(c);setPassword('');setError('');}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function navigate(v:View){setView(v);setSelected(null);setEditing(null);setError('');setNotice('');setFilter('all');setTab('overview');setDirty(false);}
 function edit(item:Item|null){const v=item?structuredClone(item.config_on_disk||item):view==='streams'?{name:'',title:''}:view==='templates'?{name:'',static:false,inputs:[]}:resource==='auth_backends'?{name:'',url:''}:{hostname:'',api_url:'',public_payload_url:'',private_payload_url:''};delete v.stats;delete v.config_on_disk;setEditing(v);setJson(JSON.stringify(v,null,2));setNotice('');}
 async function save(){if(!editing)return;setBusy(true);try{const value=JSON.parse(json);const name=value.name||value.hostname;if(!name)throw Error('Name is required.');const collection=view==='cluster'?'cluster/'+resource:view;const result=await request(api+collection+'/'+path(name),'PUT',{$reset:true,...value,...(view==='streams'&&!value.template&&value.static===undefined?{static:false}:{})});setNotice('Saved. Runtime state is shown separately.');setSelected(view==='streams'?result:null);setEditing(null);await load();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(item:Item){const name=item.name||item.hostname;if(!window.confirm(`Delete ${name}?`))return;try{await request(api+(view==='cluster'?'cluster/'+resource:view)+'/'+path(name),'DELETE');setSelected(null);setNotice('Deleted.');await load();}catch(e){setError((e as Error).message)}}
 async function stop(item:Item){try{await request(api+'streams/'+path(item.name)+'/stop','POST',{});await load();setNotice('Worker stopped. Static streams restart on reconciliation.');}catch(e){setError((e as Error).message)}}
 async function apply(validate:boolean){setBusy(true);try{await request(api+'config',validate?'POST':'PUT',JSON.parse(json));setNotice(validate?'Configuration is valid. Saved state has not changed.':'Configuration saved and applied.');if(!validate){setDirty(false);await load();}}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const visible=items.filter(i=>(i.name||i.hostname||'').toLowerCase().includes(search.toLowerCase())&&(filter==='all'||(i.disabled?'disabled':i.stats?.status||'waiting')===filter));
 if(!credentials)return <div className="login"><div className="login-card"><Logo/><h1>Media control</h1><p>Sign in to manage this FlussoniX node.</p><form onSubmit={login}><label>Username<input autoComplete="username" value={user} onChange={e=>setUser(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form><small>First working copy · {location.host}</small></div></div>;
 return <><header><Logo/><nav><button className={view==='streams'||view==='templates'?'active':''} onClick={()=>navigate('streams')}>Media <span>▾</span></button><button className={view==='config'?'active':''} onClick={()=>navigate('config')}>Config</button><button className={view==='cluster'?'active':''} onClick={()=>navigate('cluster')}>Cluster</button></nav><div className="node-label"><i className="dot"/>{node.name||'Connecting'}<span className="role">{node.role}</span></div><button onClick={()=>setCredentials('')}>Sign out</button></header>
 <div className="status-strip"><span><i className="dot"/>Node online</span><span>{node.streams?.length||0} streams</span><span>{node.active??0} viewer sessions</span><span>Output <b>{mbps(node.egress_mbps)}</b></span><span>CPU <b>{pct(node.cpu)}</b></span><span>RAM <b>{pct(node.ram)}</b></span><span className="right mono">{location.host} · v0.1.0</span></div>
 <main>{error&&<div className="error" role="alert">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}>×</button></div>}{notice&&<div className="notice" role="status">{notice}</div>}
 <div className="page-heading"><div><div className="breadcrumb">{view==='streams'||view==='templates'?'Media': 'System'} / {view[0].toUpperCase()+view.slice(1)}{selected&&' / '+selected.name}</div><h1>{selected?selected.title||selected.name:view==='streams'?'Streams':view==='templates'?'Templates':view==='config'?'Configuration':'Cluster'}</h1></div><div className="heading-actions">{selected?<><button onClick={()=>setSelected(null)}>← Streams</button><button className="primary" onClick={()=>edit(selected)}>Edit stream</button></>:view!=='config'?<><input className="search" aria-label="Search" placeholder="Search by name…" value={search} onChange={e=>setSearch(e.target.value)}/><button className="primary" onClick={()=>edit(null)}>＋ Add {view==='streams'?'stream':view==='templates'?'template':resource==='peers'?'peer':resource==='sources'?'source':'auth backend'}</button></>:<><button disabled={busy} onClick={()=>apply(true)}>Validate</button><button disabled={busy} className="primary" onClick={()=>apply(false)}>Save & apply</button></>}</div></div>
 {(view==='streams'||view==='templates')&&<div className="tabs"><button className={view==='streams'?'selected':''} onClick={()=>navigate('streams')}>Streams</button><button className={view==='templates'?'selected':''} onClick={()=>navigate('templates')}>Templates</button></div>}
 {view==='streams'&&!selected&&<><div className="metrics"><Metric label="Configured streams" value={items.length}/><Metric label="Running workers" value={items.filter(i=>i.stats?.status==='running').length}/><Metric label="Viewer sessions" value={node.active??0}/><Metric label="Output traffic" value={mbps(node.egress_mbps)}/><Metric label="Uplink utilization" value={pct(node.uplink)}/></div><div className="filterbar">{['all','running','waiting','disabled','error'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f==='error'?'Problems':f[0].toUpperCase()+f.slice(1)}</button>)}<span className="right">{visible.length} streams</span></div>
 <div className="panel table-wrap"><table><thead><tr><th>Status</th><th>Stream / title</th><th>Input</th><th>Viewers (TS)</th><th>Uptime</th><th>Transcoding</th><th/></tr></thead><tbody>{visible.map(i=><tr key={i.name}><td><Status status={i.disabled?'disabled':i.stats?.status||'waiting'}/></td><td><button className="link mono" onClick={()=>{setSelected(i);setTab('overview')}}>{i.name}</button><div className="subtext">{i.title||'—'}</div></td><td><span className="tag">{i.inputs?.[0]?.url?.split('://')[0]?.toUpperCase()||'No input'}</span></td><td className="mono">{i.stats?.online_clients||0}</td><td className="mono">{i.stats?.uptime??'—'}{i.stats?.uptime!==undefined?'s':''}</td><td>{i.transcoder?(i.transcoder.encoder==='h264_nvenc'?'NVIDIA GPU':'CPU'):i.inputs?.[0]?.url==='testsrc://'?'CPU · synthetic':'Copy'}</td><td className="actions"><button onClick={()=>edit(i)}>Edit</button><button onClick={()=>stop(i)}>Stop</button><button className="danger" onClick={()=>remove(i)}>Delete</button></td></tr>)}</tbody></table>{!visible.length&&<Empty title="No streams here" text="Add a source or an owned synthetic test stream to begin."/>}</div><div className="footnote">HLS and MPEG-TS share one worker per active stream. Viewer sessions expire after 30 seconds of inactivity once continuous playback closes.</div></>}
 {view==='streams'&&selected&&<><div className="tabs">{['overview','input','output','transcoder','auth','diagnostics'].map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div><div className="detail-grid"><section className="panel padded">{tab==='overview'?<><h2>Runtime</h2><dl><dt>Stream</dt><dd className="mono">{selected.name}</dd><dt>State</dt><dd><Status status={selected.stats?.status||'waiting'}/></dd><dt>Template</dt><dd>{selected.template||'None'}</dd><dt>Worker policy</dt><dd>{selected.static===false?'On demand':'Static'}</dd><dt>Configured input</dt><dd>{selected.inputs?.[0]?.url?.split('://')[0]?.toUpperCase()||'No input'}</dd></dl><h2>Playback</h2><p>Test HLS playback from this node.</p><button onClick={()=>setPlay(selected.name)}>Open player</button></>:tab==='output'?<><h2>Delivery endpoints</h2><dl>{['index.m3u8','fmp4/index.m3u8','mpegts','m4s','m4f'].map(f=><React.Fragment key={f}><dt>{f}</dt><dd className="mono">{location.origin}/{path(selected.name)}/{f}</dd></React.Fragment>)}</dl><p className="muted">fMP4 HLS is a separate delivery format. It does not imply Flussonic M4F/M4S compatibility.</p></>:<><h2>{tab[0].toUpperCase()+tab.slice(1)} settings</h2><pre>{JSON.stringify(tab==='input'?selected.inputs:tab==='transcoder'?selected.transcoder||{mode:'copy'}:tab==='auth'?{on_play:selected.on_play||null,token_protection:!!selected.flussonix_token_sha256}:selected.stats,null,2)}</pre><button onClick={()=>edit(selected)}>Edit configuration</button></>}</section><section className="panel padded"><h2>Saved overrides</h2><p className="muted">Explicit settings stored on disk. Effective settings include inherited template values.</p><pre>{JSON.stringify(selected.config_on_disk||selected,null,2)}</pre></section></div></>}
 {view==='templates'&&<div className="panel table-wrap"><table><thead><tr><th>Template</th><th>Input protocol</th><th>Activation</th><th>Actions</th></tr></thead><tbody>{visible.map(i=><tr key={i.name}><td className="mono">{i.name}</td><td>{i.inputs?.[0]?.url?.split('://')[0]?.toUpperCase()||'Inherited / unset'}</td><td>{i.static===false?'On demand':'Static'}</td><td className="actions"><button onClick={()=>edit(i)}>Edit</button><button className="danger" onClick={()=>remove(i)}>Delete</button></td></tr>)}</tbody></table>{!visible.length&&<Empty title="No templates configured" text="Templates provide defaults while streams retain their explicit overrides."/>}</div>}
 {view==='config'&&<div className="config-layout"><aside className="panel"><h2>Configuration</h2><button className="selected">Server configuration</button><button onClick={()=>{navigate('cluster');setResource('auth_backends')}}>Auth backends</button><div className="sidebar-note">Listen address, API credentials, role and resource limits are startup options. Restart your FlussoniX test process to change them.</div></aside><section className="panel"><div className="panel-heading"><h2>Saved configuration</h2><span className="tag">JSON · v3 subset</span></div><textarea aria-label="Server configuration JSON" className="code-editor" value={json} onChange={e=>{setJson(e.target.value);setDirty(true)}} spellCheck={false}/><div className="editor-footer">Validate checks the document without saving it. Save & apply persists it atomically.</div></section></div>}
 {view==='cluster'&&<><div className="tabs">{['peers','sources','auth_backends'].map(t=><button key={t} className={resource===t?'selected':''} onClick={()=>setResource(t)}>{t==='peers'?'CDN peers':t==='sources'?'Source servers':'Auth backends'}</button>)}</div><div className="metrics"><Metric label="This node" value={node.name||'—'}/><Metric label="Role" value={node.role||'—'}/><Metric label="Capacity" value={`${node.limit??0} sessions`}/><Metric label="Pending admissions" value={node.reserved??0}/><Metric label="Drain" value={node.drain?'Enabled':'Disabled'}/></div><section className="panel topology"><div><span className="topology-role">BALANCER</span><strong>Viewer entry point</strong><small>CPU · RAM · uplink · readiness</small></div><span className="arrow">→<small>Public redirect</small></span><div><span className="topology-role">CDN</span><strong>Selected delivery node</strong><small>One worker · shared viewer fan-out</small></div><span className="arrow">←<small>Private HLS pull</small></span><div><span className="topology-role">SOURCE</span><strong>Stream origin</strong><small>Authenticated discovery and ingest</small></div></section><div className="panel table-wrap"><table><thead><tr><th>{resource==='auth_backends'?'Backend':'Node'}</th><th>Management / auth URL</th>{resource!=='auth_backends'&&<><th>Public delivery</th><th>Private media</th></>}<th>Actions</th></tr></thead><tbody>{visible.map(i=><tr key={i.hostname||i.name}><td className="mono">{i.hostname||i.name}</td><td className="mono">{i.api_url||i.url}</td>{resource!=='auth_backends'&&<><td className="mono">{i.public_payload_url||'—'}</td><td className="mono">{i.private_payload_url||'Uses management URL'}</td></>}<td className="actions"><button onClick={()=>edit(i)}>Edit</button><button className="danger" onClick={()=>remove(i)}>Delete</button></td></tr>)}</tbody></table>{!visible.length&&<Empty title={`No ${resource.replace('_',' ')} configured`} text="Add the management and media endpoints for your test nodes."/>}</div><div className="footnote">Native cluster mode. Legacy Flussonic cluster interoperability is not yet qualified. Admission tickets expire after 5 seconds.</div></>}
 {Object.keys(caps).length>0&&<details className="capabilities"><summary>Build capabilities and compatibility</summary><pre>{JSON.stringify(caps,null,2)}</pre></details>}
 </main><footer>FlussoniX <span>Independent media server · First working copy</span><span className="right">Metrics reflect this node only</span></footer>
 {editing&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><div className="panel-heading"><h2 id="edit-title">{editing.name||editing.hostname?'Edit configuration':'Add configuration'}</h2><button aria-label="Close editor" onClick={()=>setEditing(null)}>×</button></div><div className="padded"><p className="muted">Use a source URL, or <code>testsrc://</code> for an owned synthetic stream. Unsupported protocols and features are rejected.</p>{view==='streams'&&<div className="form-grid"><label>Stream name<input value={editing.name||''} onChange={e=>{const v={...editing,name:e.target.value};setEditing(v);setJson(JSON.stringify(v,null,2))}}/></label><label>Input URL<input value={editing.inputs?.[0]?.url||''} onChange={e=>{const v={...editing,inputs:[{url:e.target.value}]};setEditing(v);setJson(JSON.stringify(v,null,2))}}/></label><label>Template<select value={editing.template||''} onChange={e=>{const v={...editing,template:e.target.value||null};setEditing(v);setJson(JSON.stringify(v,null,2))}}><option value="">None</option>{templates.map(t=><option key={t.name}>{t.name}</option>)}</select></label><label>Transcoding<select value={editing.transcoder?.encoder||'copy'} onChange={e=>{const v={...editing,transcoder:e.target.value==='copy'?null:{encoder:e.target.value,vb:900}};setEditing(v);setJson(JSON.stringify(v,null,2))}}><option value="copy">Copy</option><option value="libx264">CPU · H.264</option><option value="h264_nvenc">NVIDIA · H.264 (hardware required)</option></select></label></div>}<label>Configuration JSON<textarea className="code-editor small" aria-label="Configuration JSON" value={json} onChange={e=>{setJson(e.target.value);try{const v=JSON.parse(e.target.value);if(v&&typeof v==='object'&&!Array.isArray(v))setEditing(v)}catch{}}} spellCheck={false}/></label>{error&&<div className="error" role="alert">{error}</div>}</div><div className="modal-actions"><button onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy} onClick={save}>{busy?'Saving…':'Save'}</button></div></section></div>}
 {play&&<Player name={play} close={()=>setPlay(null)}/>}</>;
}
function Logo(){return <div className="logo">Flussoni<span>X</span></div>}
function Metric({label,value}:{label:string,value:React.ReactNode}){return <div><small>{label}</small><strong>{value}</strong></div>}
function Status({status}:{status:string}){return <span className={'status '+status}><i className="dot"/>{status[0].toUpperCase()+status.slice(1)}</span>}
function Empty({title,text}:{title:string,text:string}){return <div className="empty"><h2>{title}</h2><p>{text}</p></div>}
function Player({name,close}:{name:string,close:()=>void}){const ref=useRef<HTMLVideoElement>(null);const[token,setToken]=useState('');const[start,setStart]=useState(false);const[error,setError]=useState('');useEffect(()=>{if(!start||!ref.current)return;const url=`/${path(name)}/index.m3u8${token?'?token='+encodeURIComponent(token):''}`;const video=ref.current;let h:Hls|undefined;if(Hls.isSupported()){h=new Hls();h.loadSource(url);h.attachMedia(video);h.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)setError('Playback failed: '+d.details)});}else video.src=url;return()=>h?.destroy()},[start,name,token]);return <div className="modal-backdrop"><section className="modal player" role="dialog" aria-modal="true"><div className="panel-heading"><h2>{name}</h2><button aria-label="Close player" onClick={close}>×</button></div><div className="padded"><video ref={ref} controls autoPlay muted/><div className="form-grid"><label>Viewer token (if required)<input type="password" value={token} onChange={e=>{setStart(false);setToken(e.target.value)}}/></label><button className="primary" onClick={()=>{setError('');setStart(true)}}>Start playback</button></div>{error&&<div className="error">{error}</div>}</div></section></div>}
createRoot(document.getElementById('root')!).render(<App/>);
